apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app
  namespace: default
spec:
  interval: 15m
  path: "./repositories/example-app/k8s"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app
