apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      imagePullSecrets:
        - name: dockerhub-credentials
      containers:
      - name: example-app
        image: ptrz26/example-app
        ports:
        - containerPort: 80
