apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: guest-book
  namespace: guest-book
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/ptr26/fluxcd.git
