name: Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  changed-folders:
    runs-on: ubuntu-latest
    outputs:
      changed_folders: ${{ steps.find-changed-folders.outputs.changed_folders }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Find Changed Folders
        id: find-changed-folders
        run: |
          previous_commit_hash=$(git log --format=%H --skip=1 -n 1)
          changed_folders=$(git diff $previous_commit_hash --name-only -- './repositories/guest-book/src/' | sed 's/\/[^\/]*$//' | sort -u)
          echo "Changed folders from previous commit:"
          echo "$changed_folders"
          echo "::set-output name=changed_folders::[\"${changed_folders// /\",\"}\"]"

  build-docker:
    runs-on: ubuntu-latest
    name: Build and push docker image
    needs: [changed-folders]
    strategy:
      matrix:
        folder: ${{ fromJson(needs.changed-folders.outputs.changed_folders) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "ptrz26"
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Calculate short SHA
        run: |
          echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV
      - name: Process Changed Folders
        run: |
          output=${{ matrix.folder }}
          second_string=$(echo "$output" | cut -d '/' -f 2)
          last_string=$(echo "$output" | rev | cut -d '/' -f 1 | rev)
          concatenated_result="${second_string}-${last_string}"
          echo "IMAGE=$last_string" >> $GITHUB_ENV
          echo "CONCATENATED_RESULT=$concatenated_result" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.folder }}/Dockerfile
          push: true
          tags: ptrz26/${{ env.CONCATENATED_RESULT }}:${{ env.SHORT_SHA }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Update k8s deployment YAML
        run: |
          sed -i "s|image: ptrz26/${{ env.CONCATENATED_RESULT }}:.*|image: ptrz26/${{ env.CONCATENATED_RESULT }}:${{ env.SHORT_SHA }}|" repositories/guest-book/k8s/${{ env.IMAGE }}.yaml
      - name: Commit and push changes
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "github-action@github.com"
          git add repositories/guest-book/k8s/${{ env.IMAGE }}.yaml
          git commit -m "Update deployment.yaml with new image tag"
          git remote set-url origin https://x-access-token:${{ secrets.PAT }}@github.com/${GITHUB_REPOSITORY}.git
          git push origin main
