name: Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'fluxcd/repositories/example-app/src/index.html'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build and push docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USER }}/example-app:latest ./repositories/example-app/src
          docker push ${{ secrets.DOCKERHUB_USER }}/example-app:latest
