name: Push to Docker Hub

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'fluxcd/repositories/example-app/src/index.html'
      - 'repositories/example-app/src/index.html'

jobs:
  build-docker:
    runs-on: ubuntu-latest
    name: Build and push docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: "ptrz26"
          password: ${{ secrets.DOCKERHUB_PAT }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./repositories/example-app/src/Dockerfile
          push: true
          tags: ptrz26/example-app:latest
          labels: ${{ steps.meta.outputs.labels }}
